"""create intents and intent_outcomes tables

Revision ID: b2218948f541
Revises: c987997c1e9a
Create Date: 2026-03-08 19:58:46.907147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2218948f541'
down_revision: Union[str, Sequence[str], None] = 'c987997c1e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deterministic_id', sa.String(length=64), nullable=False),
    sa.Column('intent_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('oss_payload', sa.JSON(), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_deterministic_id'), 'intents', ['deterministic_id'], unique=True)
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    op.create_table('intent_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('recorded_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id', name='uq_outcome_intentid')
    )
    op.create_index(op.f('ix_intent_outcomes_id'), 'intent_outcomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_outcomes_id'), table_name='intent_outcomes')
    op.drop_table('intent_outcomes')
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_deterministic_id'), table_name='intents')
    op.drop_table('intents')
    # ### end Alembic commands ###
